import type { Metadata } from "next";
import '../style/settings.scss'

export const metadata: Metadata = {
  title: "Blume Landing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className="grid">
        {children}
      </body>
    </html>
  );
}
